www/routes/web.php
<?php

use App\Http\Controllers\ClienteController;
use App\Http\Controllers\EnderecoController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\UsuarioController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function () {
    return view('welcome');
});*/

Route::middleware(['auth'])->group(function () {
    Route::get('/', [HomeController::class, 'index'])->name('home');
    Route::resource('clientes', ClienteController::class);
    Route::resource('enderecos', EnderecoController::class);
    Route::resource('usuarios', UsuarioController::class);
});

Auth::routes();

//Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

www/app/Models/Cliente.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Cliente extends Model
{
    use HasFactory;

    protected $table = "clientes";
    protected $fillable = [
        "id_cliente", "id_endereco", "id_endereco_tipo", "nome",
        "cnpj", "telefone", "responsavel", "email"
      ];
    protected $primaryKey = 'id_cliente';

    protected $casts = [
        'id_endereco' => 'array'
    ];

    public function enderecos()
    {
        return $this->hasMany(Endereco::class, 'id_cliente');
    }

    public function enderecotipo()
    {
        return $this->morphToMany(Enderecotipo::class, 'id_endereco_tipo');
    }
}

www/app/Http/Controllers/ClienteController.php
<?php

namespace App\Http\Controllers;

use App\Models\Cliente;
use App\Models\Endereco;
use App\Models\Enderecotipo;
use Illuminate\Http\Request;

class ClienteController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $this->authorize('view', Usuario::class);
        $clientes = Cliente::all();
        return view('clientes.index', compact('clientes'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $this->authorize('create', Usuario::class);
        return view('clientes.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->authorize('create', Usuario::class);
        try {
            $dados = $request->all();
            $cliente = Cliente::create($dados);
            return redirect()->route('cliente.endereco', $cliente->id_cliente)->with('status', 'Cliente cadastrado com sucesso!');
        } catch (\Throwable $th) {
            return response()->json([
                'success' => false,
                'message' => "Erro ao cadastrar cliente",
                'error' => $th
            ]);
        }


    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $this->authorize('view', Usuario::class);
        $clientes = Cliente::find($id);
        $enderecos = Endereco::all();
        $enderecotipo = Enderecotipo::all();
        return view('clientes.show', compact('clientes', 'enderecos', 'enderecotipo'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $this->authorize('update', Usuario::class);
        $clientes = Cliente::find($id);
        $enderecos = Endereco::all();
        $enderecotipo = Enderecotipo::all();
        return view('clientes.edit', compact('clientes', 'enderecos', 'enderecotipo'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->authorize('update', Usuario::class);
        $dados = $request->all();
        Cliente::find($id)->update($dados);
        return redirect()->route('clientes.index')->with('success', "Cliente atualizado com sucesso!");

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->authorize('delete', Usuario::class);
        try {
            Cliente::find($id)->delete();
            return redirect()->route('clientes.index')->with('success', "Cliente excluido com sucesso!");
        } catch (\Throwable $th) {
            return response()->json([
                'success' =>false,
                'mensage' => "Erro ao deletar cliente"
            ]);
        }
    }
}

www/resources/views/clientes/create.blade.php
@extends('layouts.app')

@section('content')
    @if (session('message'))
        <div class="alert alert-success" role="alert">
            {{ session('message') }}
        </div>
    @endif
    <div class="card">
        <!-- Nav tabs -->
        <ul class="nav nav-tabs">
            <li class="nav-item">
                <a class="nav-link active" data-toggle="tab" href="#home">Empresa</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" @if (session('control_aba', '1')) {{ 'class="active"' }} @endif data-toggle="tab" href="#menu1">Endereços</a>
            </li>
        </ul>

        <!-- Tab panes -->
        <div class="tab-content">
            <div class="tab-pane active container" id="home">
                <div class="card-body">
                    <form method="POST" action="{{ route('clientes.store') }}" class="form-horizontal row">
                        @csrf
                        <div class="col-md-6">
                            <label for="nome" class="control-label">Empresa</label>
                            <input type="text" class="form-control" id="nome" name="nome" placeholder="Nome da Empresa"
                                value="" maxlength="50" required="">
                        </div>
                        <div class="col-md-3">
                            <label for="cnpj" class="control-label">CNPJ</label>
                            <input type="text" class="form-control cnpj" id="cnpj" name="cnpj" placeholder="CNPJ" value=""
                                maxlength="50" required="">
                        </div>
                        <div class="col-md-3">
                            <label for="telefone" class="control-label">Telefone</label>
                            <input type="text" class="form-control telefone" id="telefone" name="telefone"
                                placeholder="Telefone" value="" maxlength="50" required="">
                        </div>
                        <div class="col-md-6">
                            <label for="responsavel" class="control-label">Responsável</label>
                            <input type="text" class="form-control" id="responsavel" name="responsavel"
                                placeholder="Enter Name" value="" maxlength="50" required="">
                        </div>
                        <div class="col-md-6">
                            <label for="email" class="control-label">E-mail</label>
                            <input type="text" class="form-control" id="email" name="email" placeholder="E-mail" value=""
                                maxlength="50" required="">
                            <br>
                        </div>
                        <div class="modal-footer col-sm-offset-2 col-sm-12">
                            <button type="submit" class="btn btn-primary">Adicionar</button>
                        </div>
                    </form>
                </div>
            </div>
            <div class="tab-pane container" @if (session('control_aba', '1')) {{ 'class="active"' }} @endif id="menu1">
                <div class="card-body">
                    <form method="POST" name="id_cliente" action="{{ route('clientes.store') }}"
                        class="form-horizontal row">
                        @csrf
                        <input type="hidden" name="id_cliente[]" id="id_cliente">
                        <div class="col-md-3">
                            <label for="cep" class="control-label">CEP</label>
                            <div class="col-sm-12">
                                <input type="text" class="form-control cep" id="cep" name="cep" placeholder="CEP" value=""
                                    maxlength="50" required="">
                            </div>
                        </div>
                        <div class="col-md-7">
                            <label for="logradouro" class="control-label">Logradouro</label>
                            <div class="col-sm-12">
                                <input type="text" class="form-control" id="logradouro" name="logradouro"
                                    placeholder="Logradouro" value="" maxlength="50" required="">
                            </div>
                        </div>
                        <div class="col-md-2">
                            <label for="numero" class="control-label">Número</label>
                            <div class="col-sm-12">
                                <input type="text" class="form-control" id="numero" name="numero" placeholder="Nº" value=""
                                    maxlength="50" required="">
                            </div>
                        </div>
                        <div class="col-md-12">
                            <label for="complemento" class="control-label">Complemento</label>
                            <div class="col-sm-12">
                                <input type="text" class="form-control" id="complemento" name="complemento"
                                    placeholder="Complemento" value="" maxlength="50" required="">
                            </div>
                        </div>
                        <div class="col-md-4">
                            <label for="bairro" class="control-label">Bairro</label>
                            <div class="col-sm-12">
                                <input type="text" class="form-control" id="bairro" name="bairro" placeholder="Bairro"
                                    value="" maxlength="50" required="">
                            </div>
                        </div>
                        <div class="col-md-4">
                            <label for="cidade" class="control-label">Cidade</label>
                            <div class="col-sm-12">
                                <input type="text" class="form-control" id="cidade" name="cidade" placeholder="Cidade"
                                    value="" maxlength="50" required="">
                            </div>
                        </div>
                        <div class="col-md-4">
                            <label for="estado" class="control-label">Estado</label>
                            <div class="col-sm-12">
                                <input type="text" class="form-control" id="estado" name="estado" placeholder="Estado"
                                    value="" maxlength="50" required="">
                            </div>
                        </div>
                        <div class="modal-footer col-sm-offset-2 col-sm-12">
                            <button type="submit" class="btn btn-primary" id="saveBtn" value="create">Adicionar</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <script type="text/javascript">
        $(function() {

            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });

            //exibir modal adicionar endereços//
            $('#createNewCliente').click(function() {
                $('#saveBtn').val("create-cliente");
                $('#id_cliente').val('');
                $('#clienteForm').trigger("reset");
                $('#modelHeading').html("Adicionar novo endereço");
                $('#ajaxModel').modal('show');
            });

            $('#saveBtn').click(function(e) {
                e.preventDefault();
                $(this).html('Sending..');

                $.ajax({
                    data: $('#clienteForm').serialize(),
                    url: "{{ route('clientes.store') }}",
                    type: "POST",
                    dataType: 'json',
                    success: function(data) {

                        $('#clienteForm').trigger("reset");
                        $('#ajaxModel').modal('hide');
                        table.draw();

                    },
                    error: function(data) {
                        console.log('Error:', data);
                        $('#saveBtn').html('Salvar Alterações');
                    }
                });
            });
        });

        //DataTable da Tabela//
        $(document).ready(function() {
            $('.tabela').DataTable({
                pageLength: 10,
                responsive: true,
            });
        });
        //Campos com mascara//
        $(document).ready(function() {
            $('.telefone').mask("(00) 00000-0000", {
                placeholder: "(__) _ ____-____"
            });
            $('.cnpj').mask("00.000.000/0000-00", {
                placeholder: "__.___.___/____-__"
            });
            $('.cep').mask("00.000-000", {
                placeholder: "__.___-___"
            });
        });
        //carregamento do endereço automatico//
        $(document).ready(function() {

            function limpa_formulário_cep() {
                // Limpa valores do formulário de cep.
                $("#logradouro").val("");
                $("#complemento").val("");
                $("#bairro").val("");
                $("#cidade").val("");
                $("#estado").val("");
            }

            //Quando o campo cep perde o foco.
            $("#cep").blur(function() {

                //Nova variável "cep" somente com dígitos.
                var cep = $(this).val().replace(/\D/g, '');

                //Verifica se campo cep possui valor informado.
                if (cep != "") {

                    //Expressão regular para validar o CEP.
                    var validacep = /^[0-9]{8}$/;

                    //Valida o formato do CEP.
                    if (validacep.test(cep)) {

                        //Preenche os campos com "..." enquanto consulta webservice.
                        $("#logradouro").val("...");
                        $("#complemento").val("");
                        $("#bairro").val("");
                        $("#cidade").val("...");
                        $("#estado").val("...");
                        $("#complemento").val("...");

                        //Consulta o webservice viacep.com.br/
                        $.getJSON("https://viacep.com.br/ws/" + cep + "/json/?callback=?", function(dados) {

                            if (!("erro" in dados)) {
                                //Atualiza os campos com os valores da consulta.
                                $("#logradouro").val(dados.logradouro);
                                $("#complemento").val(dados.complemento);
                                $("#bairro").val(dados.bairro);
                                $("#cidade").val(dados.localidade);
                                $("#estado").val(dados.uf);

                            } //end if.
                            else {
                                //CEP pesquisado não foi encontrado.
                                limpa_formulário_cep();
                                alert("CEP não encontrado.");
                            }
                        });
                    } //end if.
                    else {
                        //cep é inválido.
                        limpa_formulário_cep();
                        alert("Formato de CEP inválido.");
                    }
                } //end if.
                else {
                    //cep sem valor, limpa formulário.
                    limpa_formulário_cep();
                }
            });
        });

    </script>

@endsection

www/resources/views/clientes/index.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="header-expand justify-content-lg-end text-lg-right">
                        @can('create', App\Usuario::class)
                        <a class="btn btn-success" href="{{ route('clientes.create') }}"><i class="fa fa-user-plus"></i>
                            Adicionar novo cliente</a>
                        @endcan
                    </div>

                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif

                        <table id="mytable" class="table">
                            <thead>
                                <tr>
                                    <th scope="col">ID</th>
                                    <th scope="col">Empresa</th>
                                    <th scope="col">CNPJ</th>
                                    <th scope="col">Telefone</th>
                                    <th scope="col">Responsável</th>
                                    <th scope="col">Ações</th>
                                </tr>
                            </thead>
                            @foreach ($clientes as $cliente)
                                <tbody>
                                    <tr>
                                        <td>{{ $cliente->id_cliente }}</td>
                                        <td>{{ $cliente->nome }}</td>
                                        <td>{{ $cliente->cnpj }}</td>
                                        <td>{{ $cliente->telefone }}</td>
                                        <td>{{ $cliente->responsavel }}</td>
                                        <td>
                                            <div class="btn-group btn-group-sm">
                                                @can('view', App\Usuario::class)
                                                    <a class="btn btn-primary"
                                                        href="{{ route('clientes.show', $cliente->id_cliente) }}">
                                                        <i class="fa fa-eye"></i>
                                                    </a>
                                                @endcan
                                                @can('update', App\Usuario::class)
                                                    <a class="btn btn-success"
                                                        href="{{ route('clientes.edit', $cliente->id_cliente) }}">
                                                        <i class="fa fa-edit"></i>
                                                    </a>
                                                @endcan
                                                @can('delete', App\Usuario::class)
                                                    <a class="btn btn-danger delete-user"
                                                        data-clientes="{{ $cliente->id_cliente }}">
                                                        <i class="fa fa-trash"></i>
                                                    </a>
                                                @endcan
                                            </div>
                                        </td>
                                    </tr>
                                </tbody>
                            @endforeach
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- MODAL CADASTRO-->
    <div class="modal fade" id="ajaxModel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title" id="modelHeading"></h4>
                </div>
                <div class="modal-body">
                    <form id="clienteForm" name="clienteForm" class="form-horizontal">
                        <input type="hidden" name="id_cliente" id="id_cliente">
                        <div class="form-group">
                            <label for="nome" class="col-sm-2 control-label">Empresa</label>
                            <div class="col-sm-12">
                                <input type="text" class="form-control" id="nome" name="nome" placeholder="Enter Name"
                                    value="{{ old('nome') }}" maxlength="50" required="">
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label">Details</label>
                            <div class="col-sm-12">
                                <textarea id="detail" name="detail" required="" placeholder="Enter Details"
                                    class="form-control"></textarea>
                            </div>
                        </div>

                        <div class="col-sm-offset-2 col-sm-10">
                            <button type="submit" class="btn btn-primary" id="saveBtn" value="create">Save changes
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <script type="text/javascript">
        $(document).ready(function() {
            $('#mytable').DataTable();
        });

        $('#createNewCliente').click(function() {
            $('#saveBtn').val("create-cliente");
            $('#id_cliente').val('');
            $('#clienteForm').trigger("reset");
            $('#modelHeading').html("Adicionar novo cliente");
            $('#ajaxModel').modal('show');
        });

        $('body').on('click', '.editCliente', function() {
            var id_cliente = $(this).data('id_cliente');
            $.get("{{ route('clientes.index') }}" + '/' + id_cliente + '/edit', function(data) {
                $('#modelHeading').html("Editar Cliente");
                $('#saveBtn').val("edit-user");
                $('#ajaxModel').modal('show');
                $('#id_cliente').val(data.id_cliente);
                $('#nome').val(data.nome);
                $('#cnpj').val(data.cnpj);
                $('#telefone').val(data.telefone);
                $('#responsavel').val(data.responsavel);
                $('#email').val(data.email);
            })
        });

        $('#saveBtn').click(function(e) {
            e.preventDefault();
            $(this).html('Sending..');

            $.ajax({
                data: $('#clienteForm').serialize(),
                url: "{{ route('clientes.store') }}",
                type: "POST",
                dataType: 'json',
                success: function(data) {

                    $('#clienteForm').trigger("reset");
                    $('#ajaxModel').modal('hide');
                    table.draw();

                },
                error: function(data) {
                    console.log('Error:', data);
                    $('#saveBtn').html('Salvar Alterações');
                }
            });
        });

        $('body').on('click', '.deleteCliente', function() {

            var id_endereco = $(this).data("id");
            confirm("Are You sure want to delete !");

            $.ajax({
                type: "DELETE",
                url: "{{ route('clientes.store') }}" + '/' + id_endereco,
                success: function(data) {
                    table.draw();
                },
                error: function(data) {
                    console.log('Error:', data);
                }
            });
        });
        //Método Delete//
        $(document).on('click', '.delete-user', function(e) {
            e.preventDefault();
            if (confirm('Tem certeza que deseja excluir?')) {
                var id = $(this).data('clientes');
                var $bt = $(this);
                $.ajaxSetup({
                    headers: {
                        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                    }
                });
                $.ajax({
                    type: 'delete',
                    dataType: "JSON",
                    url: 'clientes/' + id, //rota que deleta
                    beforeSend: function() {}
                }).done(function(response) {
                    console.log(response);
                    try {
                        //response = JSON.parse(response);
                        if (response.success) {
                            var $tr = $bt.closest('tr');
                            $tr.addClass('animated fadeOutLeft');
                            setTimeout(function() {
                                $tr.remove();
                            }, 1000);
                        } else {
                            alert(response.message);
                        }
                    } catch (e) {
                        alert('Ocorreu um erro desconhecido, por favor tente novamente mais tarde.',
                            'Erro!');
                    }
                });
            }
        });

    </script>


@endsection

www/resources/views/clientes/show.blade.php
@extends('layouts.app')

@section('content')
<div class="callout">
    <h3>Dados Empresarial</h3>
    <hr>
    <div class="row">
        <div class="col-lg-6 row">
            <div class="col-lg-4">
                <h4>Razão Social</h4>
                <p>{{$clientes->nome}}</p>
            </div>
            <div class="col-lg-4">
                <h4>CNPJ</h4>
                <p>{{$clientes->cnpj}}</p>
            </div>
            <div class="col-lg-4">
                <h4>Telefone</h4>
                <p>{{$clientes->telefone}}</p>
            </div>
            <div class="col-lg-4">
                <h4>Responsável</h4>
                <p>{{$clientes->responsavel}}</p>
            </div>
            <div class="col-lg-4">
                <h4>E-mail</h4>
                <p>{{$clientes->email}}</p>
            </div>
        </div>
        <div class="col-lg-6 row">
            <table id="table-endereco" class="table data-table clientes">
                <thead>
                    <tr>
                        <th scope="col">CEP</th>
                        <th scope="col">Logradouro</th>
                        <th scope="col">Cidade</th>
                        <th scope="col">Estado</th>
                        <th scope="col">Tipo</th>
                    </tr>
                </thead>
                @foreach ($enderecos as $endereco)
                    @if ($clientes->id_cliente == $endereco->id_cliente)
                        <tbody>
                            <tr>
                                <th scope="row">{{ $endereco->cep }}</th>
                                <td>{{ $endereco->logradouro, $endereco->numero, $endereco->bairro }}</td>
                                <td>{{ $endereco->cidade }}</td>
                                <td>{{ $endereco->estado }}</td>
                                @foreach ($enderecotipo as $tipo)
                                    @if ($endereco->id_endereco_tipo == $tipo->id_endereco_tipo)
                                        <td value="{{ $tipo->id_endereco_tipo }}">
                                            <span class="@if ($tipo->id_endereco_tipo ===
                                                1) ? 'badge bg-success' : '' @endif">{{ $tipo->descricao }}</span>
                                        </td>
                                    @endif
                                @endforeach
                            </tr>
                        </tbody>
                    @endif
                @endforeach
            </table>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function() {
        $('#table-endereco').DataTable();
    });
    //Método Delete//
    $(document).on('click', '.delete-user', function(e) {
        e.preventDefault();
        if (confirm('Tem certeza que deseja excluir?')) {
            var id_endereco = $(this).data('enderecos');
            var $bt = $(this);
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });
            $.ajax({
                type: 'delete',
                dataType: "JSON",
                url: 'enderecos/' + id_endereco, //rota que deleta
                beforeSend: function() {}
            }).done(function(response) {
                console.log(response);
                try {
                    //response = JSON.parse(response);
                    if (response.success) {
                        var $tr = $bt.closest('tr');
                        $tr.addClass('animated fadeOutLeft');
                        setTimeout(function() {
                            $tr.remove();
                        }, 1000);
                    } else {
                        alert(response.message);
                    }
                } catch (e) {
                    alert('Ocorreu um erro desconhecido, por favor tente novamente mais tarde.',
                        'Erro!');
                }
            });
        }
    });

</script>

@endsection