www/routes/web.php
<?php

use App\Http\Controllers\ClienteController;
use App\Http\Controllers\EnderecoController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\UsuarioController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function () {
    return view('welcome');
});*/

Route::middleware(['auth'])->group(function () {
    Route::get('/', [HomeController::class, 'index'])->name('home');
    Route::resource('clientes', ClienteController::class);
    Route::resource('enderecos', EnderecoController::class);
    Route::resource('usuarios', UsuarioController::class);
});

Auth::routes();

//Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

www/app/Http/Controllers/UsuarioController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use App\Models\Userstipo;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;

class UsuarioController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $usuarios = User::all();
        $tipo = Userstipo::all();
        return view('usuarios.index', compact('usuarios', 'tipo'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $tipo = Userstipo::all();
        return view('usuarios.create', compact('tipo'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $dados = $request->all();
        $dados ['password'] = Hash::make($request->password);
        User::create($dados);
        return redirect()->route('usuarios.index')->with('success', "Usuário Cadastrado com sucesso!");
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $tipos = Userstipo::all();
        $usuarios = User::find($id);
        return view('usuarios.edit', compact('tipos', 'usuarios'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $dados = $request->all();
        $dados ['password'] = Hash::make($request->password);
        User::find($id)->update($dados);
        return redirect()->route('usuarios.index')->with('success', "Usuário atualizado com sucesso!");
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {
            User::find($id)->delete();
            return response()->json(['success'=>true, 'message'=> "Usuário deletado com sucesso!"], 200);
        } catch (\Throwable $th) {
            return response()->json([
                'success' =>false,
                'mensage' => "Erro ao deletar usuário"
            ]);
        }
    }
}

www/resources/views/usuarios/create.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="header-expand justify-content-lg-end text-lg-right">
                    </div>

                    <div class="card-body">
                        <form class="row g-3" action="{{route('usuarios.store')}}" method="POST">
                            @csrf
                            <div class="col-md-6">
                                <label for="name" class="form-label">Nome</label>
                                <input type="text" class="form-control" id="name" name="name" placeholder="Nome">
                            </div>
                            <div class="col-md-6">
                                <label for="email" class="form-label">E-mail</label>
                                <input type="email" class="form-control" id="email" name="email" placeholder="E-mail">
                            </div>
                            <div class="col-4">
                                <label for="password" class="form-label">Senha</label>
                                <input type="password" class="form-control" id="password" name="password" placeholder="Senha">
                            </div>
                            <div class="col-4">
                                <label for="confirm-password" class="form-label">Confirmar senha</label>
                                <input type="password" class="form-control" id="confirm-password" placeholder="Confirmar senha">
                            </div>
                            <div class="col-md-4">
                                <label for="inputCity" class="form-label">Permissões</label>
                                <select id="id_users_tipo" name="id_users_tipo" class="form-control">
                                    @foreach ($tipo as $item)
                                        <option value="{{ $item->id_users_tipo }}">
                                            {{ $item->descricao }}
                                        </option>
                                    @endforeach
                                </select>
                                <br>
                            </div>
                            <div class="modal-footer col-12">
                                <button type="submit" class="btn btn-primary">Adicionar</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

www/resources/views/usuarios/edit.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="header-expand justify-content-lg-end text-lg-right">
                    </div>

                    <div class="card-body">
                        <form class="row g-3" action="{{ route('usuarios.update', $usuarios->id) }}" method="POST">
                            @method('PUT')
                            @csrf
                            <div class="col-md-6">
                                <label for="name" class="form-label">Nome</label>
                                <input type="text" class="form-control" id="name" name="name" value="{{ $usuarios->name }}">
                            </div>
                            <div class="col-md-6">
                                <label for="email" class="form-label">E-mail</label>
                                <input type="email" class="form-control" id="email" name="email"
                                    value="{{ $usuarios->email }}">
                            </div>
                            <div class="col-4">
                                <label for="password" class="form-label">Nova Senha</label>
                                <input type="password" class="form-control" id="password" name="password"
                                    placeholder="Nova Senha">
                            </div>
                            <div class="col-4">
                                <label for="confirm-password" class="form-label">Confirmar nova senha</label>
                                <input type="password" class="form-control" id="confirm-password"
                                    placeholder="Confirmar nova senha">
                            </div>
                            <div class="col-md-4">
                                <label for="inputCity" class="form-label">Permissões</label>
                                <select id="id_users_tipo" name="id_users_tipo" class="form-control">
                                    @foreach ($tipos as $tipo)
                                        <option value="{{ $tipo->id_users_tipo }}"
                                            {{ isset($usuarios->id_users_tipo) && $usuarios->id_users_tipo == $tipo->id_users_tipo ? 'selected' : '' }}>
                                            {{ $tipo->descricao }}
                                        </option>
                                    @endforeach
                                </select>
                                <br>
                            </div>
                            <div class="modal-footer col-12">
                                <button type="submit" class="btn btn-primary">Adicionar</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

www/resources/views/usuarios/index.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="header-expand justify-content-lg-end text-lg-right">
                        @can('create', App\Usuario::class)
                            <a class="btn btn-success" href="{{route('usuarios.create')}}"><i class="fa fa-user-plus"></i>
                                Adicionar novo usuario</a>
                        @endcan
                    </div>

                    <div class="card-body">
                        @if (session('success'))
                            <div class="alert alert-success" role="alert">
                                {{ session('success') }}
                            </div>
                        @endif

                        <table id="mytable" class="table">
                            <thead>
                                <tr>
                                    <th scope="col">ID</th>
                                    <th scope="col">Nome</th>
                                    <th scope="col">E-mail</th>
                                    <th scope="col">Permissões</th>
                                    <th scope="col">Ações</th>
                                </tr>
                            </thead>
                            @foreach ($usuarios as $usuario)
                                <tbody>
                                    <tr>
                                        <td>{{ $usuario->id }}</td>
                                        <td>{{ $usuario->name }}</td>
                                        <td>{{ $usuario->email }}</td>
                                        @foreach ($tipo as $item)
                                            @if ($usuario->id_users_tipo == $item->id_users_tipo)
                                                <td>{{ $item->descricao }}</td>
                                            @endif
                                        @endforeach
                                        <td>
                                            <div class="btn-group btn-group-sm">
                                                @can('update', App\Usuario::class)
                                                    <a class="btn btn-success"
                                                        href="{{ route('usuarios.edit', $usuario->id) }}">
                                                        <i class="fa fa-edit"></i>
                                                    </a>
                                                @endcan
                                                @can('delete', App\Usuario::class)
                                                    <a class="btn btn-danger delete-user" data-usuarios="{{ $usuario->id }}">
                                                        <i class="fa fa-trash"></i>
                                                    </a>
                                                @endcan
                                            </div>
                                        </td>
                                    </tr>
                                </tbody>
                            @endforeach
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script type="text/javascript">
        $(document).ready(function() {
            $('#mytable').DataTable();
        });
        //Método Delete//
        $(document).on('click', '.delete-user', function(e) {
            e.preventDefault();
            if (confirm('Tem certeza que deseja excluir?')) {
                var id = $(this).data('usuarios');
                var $bt = $(this);
                $.ajaxSetup({
                    headers: {
                        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                    }
                });
                $.ajax({
                    type: 'delete',
                    dataType: "JSON",
                    url: 'usuarios/' + id, //rota que deleta
                    beforeSend: function() {}
                }).done(function(response) {
                    console.log(response);
                    try {
                        //response = JSON.parse(response);
                        if (response.success) {
                            var $tr = $bt.closest('tr');
                            $tr.addClass('animated fadeOutLeft');
                            setTimeout(function() {
                                $tr.remove();
                            }, 1000);
                        } else {
                            alert(response.message);
                        }
                    } catch (e) {
                        alert('Ocorreu um erro desconhecido, por favor tente novamente mais tarde.',
                            'Erro!');
                    }
                });
            }
        });

    </script>
@endsection